### ISSUE TITLE
Block lags game when broken

### ISSUE THREAD

**Issue by Rubyz67** [mk0003/RigMod#2]
https://user-images.githubusercontent.com/75499681/120511213-31083980-c398-11eb-9db7-d27b35246b73.mov

**Comment by Rubyz67** [comment]
Mod List:

[Forge] Wildfire Female Gender Mod-2.5.3.jar
abnormals_core-1.16.5-3.1.1.jar
AkashicTome-1.4-16.jar
alexsmobs-1.10.1.jar
angelring-1.16.5-1.3.4.1.jar
AoA3-3.5-1.16.5-Beta-5.jar
Apotheosis-1.16.4-4.6.1.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
appliedenergistics2-8.3.1.jar
Aquaculture-1.16.5-2.1.19.jar
ars_nouveau-1.16.5-1.18.jar
astralsorcery-1.16-1.16.5-1.13.12.jar
atmospheric-1.16.5-3.1.0.jar
Atum-1.16.5-2.2.4.jar
AutoRegLib-1.6-49.jar
autumnity-1.16.5-2.1.1.jar
BasicNetherOres-1.16.5-5.5.0.jar
betteranimalsplus-1.16.5-10.2.0.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
betterendforge-1.16.4-1.6.0.jar
betterweather-1.2.9.jar
BiomesOPlenty-1.16.5-13.1.0.469-universal.jar
blame-1.16.5-3.1.0-forge.jar
Bloodcraft 5 1.16.5 1.9.9.jar
BloodMagic-1.16.4-3.1.0-15.jar
Bookshelf-1.16.5-10.1.11.jar
caelus-forge-1.16.5-2.1.3.0.jar
carryon-1.16.5-1.15.3.13.jar
ChanceCubes-1.16.5-5.0.2.421.jar
chocolate-1.3.0-1.16.4.jar
citadel-1.6.3.jar
ClientTweaks_1.16.3-5.3.0.jar
Clumps-6.0.0.24.jar
CodeChickenLib-1.16.4-3.5.1.408-universal.jar
comforts-forge-1.16.5-4.0.0.4.jar
configured-1.0.1-1.16.3.jar
Controlling-7.0.0.20.jar
CosmeticArmorReworked-1.16.5-v2.jar
Cucumber-1.16.4-4.1.9.jar
curios-forge-1.16.5-4.0.5.1.jar
curiouselytra-forge-1.16.5-4.0.2.3.jar
curiousshulkerboxes-forge-1.16.5-4.0.1.0.jar
Cyclic-1.16.5-1.2.8.jar
DarkUtilities-1.16.5-8.0.9.jar
Ding-1.16.5-1.3.0.jar
Druidcraft-1.16.5-0.4.52.jar
DungeonCrawl-1.16.3-2.2.4.jar
DynamicTrees-1.16.5-0.10.0-Beta14.jar
eidolon-0.2.7.jar
elevatorid-1.16.5-1.7.13.jar
EnderStorage-1.16.4-2.7.1.166-universal.jar
EntityCulling-1.16.5-2.1.6.jar
environmental-1.16.5-1.0.0.jar
fakeblocks-1.16.5-1.0.2.jar
FastFurnace-1.16.4-4.4.0.jar
FastWorkbench-1.16.4-4.5.1.jar
forbidden_arcanus-16.2.0-beta-3.jar
Futurepack-1.16.4-31.2.6826.jar
gaiadimension-1.16.5-1.3.3.jar
geckolib-forge-1.16.5-3.0.36.jar
Gobber2-Forge-1.16.5-2.3.50.jar
Guide-API-VP-1.16.4-2.2.1.jar
iceandfire-2.1.6-1.16.4.jar
inventorypets-1.16.5-2.0.14.jar
ironchest-1.16.4-11.2.10.jar
jei-1.16.5-7.7.0.101.jar
journeymap-1.16.5-5.7.1.jar
JustEnoughResources-1.16.5-0.12.1.119.jar
Lollipop-1.16.5-3.2.9.jar
Mantle-1.16.5-1.6.103.jar
Mekanism-1.16.5-10.0.21.448.jar
MekanismAdditions-1.16.5-10.0.21.448.jar
MekanismGenerators-1.16.5-10.0.21.448.jar
MekanismTools-1.16.5-10.0.21.448.jar
minecolonies-0.14.197-ALPHA-universal.jar
morevanillalib-1.16.4-1.4.0.jar
MouseTweaks-2.14-mc1.16.2.jar
mowziesmobs-1.5.16.jar
MysticalAgradditions-1.16.4-4.1.5.jar
MysticalAgriculture-1.16.4-4.1.8.jar
notenoughcrashes-3.2.0-forge.jar
obfuscate-0.6.1-1.16.3.jar
observerlib-1.16.5-1.5.3.jar
OptiFine_1.16.5_HD_U_G8.jar
OreExcavation-1.8.157.jar
overloadedarmorbar-5.1.0.jar
Patchouli-1.16.4-51.jar
performant-1.16.2-5-3.64m.jar
Placebo-1.16.4-4.5.0.jar
polymorph-forge-1.16.5-0.24.jar
Powah-1.16.5-2.3.16.jar
prefab-1.6.5.4.jar
ProjectE-1.16.5-PE1.0.1B.jar
Quark-r2.4-312.jar
QuarkOddities-1.16.3.jar
randompatches-2.4.4-forge.jar
rats-7.2.0-1.16.5.jar
refinedstorage-1.9.12.jar
refinedstorageaddons-0.7.2.jar
reliquary-1.16.5-1.3.5.1098.jar
repurposed_structures-1.16.5-2.6.6-forge.jar
rigmod-1.16.5-1.3.jar
Runelic-1.16.5-7.0.1.jar
ScalingHealth-1.16.5-4.0.5+5.jar
SereneSeasons-1.16.5-4.0.1.91-universal.jar
shutupexperimentalsettings-1.0.3.jar
silent-lib-1.16.3-4.9.6.jar
smoothboot-forge-1.16.4-1.2.2.jar
solcarrot-1.16.3-1.9.10.jar
Space-Bosstools-1.16.5-5.2c.jar
spark-forge.jar
SpartanShields-1.16.5-2.1.2.jar
SpartanWeaponry-1.16.4-2.1.0-beta-4.jar
StorageDrawers-1.16.3-8.2.2.jar
structurize-0.13.175-ALPHA-universal.jar
swingthroughgrass-1.16.4-1.5.3.jar
TConstruct-1.16.5-3.0.4.171.jar
Terridus_1.16.5_V3.1.jar
TheAbyss2 1.9.7 1.16.5.jar
theoneprobe-1.16-3.1.4.jar
tombstone-1.16-6.4.1.jar
torchmaster-2.3.7.jar
twilightforest-1.16.5-4.0.490-universal.jar
Ultimate SkyBlock Resource Generator-1.16.5-3.0.jar
valhelsia_core-16.0.8.jar
valhelsia_structures-1.16.5-0.1.1.jar
VampiresNeedUmbrellas-1.16.5-1.1.2.jar
Vampirism-1.16.4-1.7.11.jar
VampirismIntegrations-1.16.4-1.5.0.jar
vanillahammers-1.16.4-2.2.0.jar
voidworld-1.16.5-1.0.0.jar
Waystones_1.16.5-7.6.2.jar
world_blender-1.16.5-3.1.4.jar
Wyrmroost-1.16.3-1.2.11.jar
xptome-1.16.5-v2.1.2.jar
YungsApi-1.16.4-Forge-6.jar

**Comment by mk0003** [comment]
Can you post your rigmod-server.toml config file in your save folder if you edited it? Also I don't have my computer with me now but when I get a chance I will test the mod with the modlist you provided so I can understand the issue. Thanks!

**Comment by Rubyz67** [comment]
i didnt edit a thing

**Comment by Rubyz67** [comment]
[Random Items -Forge.zip](https://github.com/mk0003/RigMod/files/6601030/Random.Items.-Forge.zip)
you can import it into curseforge the modpack^^^

**Comment by Rubyz67** [comment]
did u fix it?

**Comment by Rubyz67** [comment]
r u ded?

**Comment by Rubyz67** [comment]
merhaba, rigmod'un onları düşürmemesi için bazı modların nasıl kara listeye alınacağına dair bir örnek gösterebilir misiniz?

**Comment by Rubyz67** [comment]
just answer me goddammit
